on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'src/main/**'
      - 'build.gradle'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            application:
              - 'build.gradle'
              - 'src/**'
              
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: 'gradle'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up gradle.properties
        run: |
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> $GITHUB_WORKSPACE/gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> $GITHUB_WORKSPACE/gradle.properties

      - name: Deploy to Maven Central
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean publish

  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Version From Branch Name
        id: extract_version
        run: |
          echo "pull_request: ${{ github.event.pull_request.head.ref }}"
          
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          
            echo "BRANCH_NAME: $BRANCH_NAME"
          
            if [[ "$BRANCH_NAME" =~ ^release\/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
              VERSION="${BASH_REMATCH[1]}"
              echo "VERSION: $VERSION"
            else
              VERSION="No version in branch name"
            fi
          
            echo "::set-output name=version::$VERSION"
          else 
            echo "No merge event detected"
          fi

      - name: Create Release
        if: steps.extract_version.outputs.version != ''
        run: |
          TAG_NAME="v${VERSION}"
          echo "TAG_NAME: $TAG_NAME"
          gh release create "$TAG_NAME" --title "$TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.extract_version.outputs.version }}
